package com.voson.dataant.firstanalyze.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Generated by Mr.Robot(Author:crazy_rain)
 * ReadMe:
 * ChangeLog:
 */

@Entity
@Table(name = "first_analyze_rule")
public class FirstAnalyzeRule implements java.io.Serializable  {

	private static final long serialVersionUID = 1L;
	/** 
	 *  序号
	 */ 
	@Id
	private Long id ;
	/** 
	 *  插入时间
	 */ 
	private java.util.Date insertTime ;
	/** 
	 *  最近执行时间
	 */ 
	private java.util.Date lastRunTime ;
	/** 
	 *  任务优先级
	 */ 
	private Long taskPriority ;
	/** 
	 * 规则状态 
	 */ 
	private Long runStatus ;
	/** 
	 *  耗时
	 */ 
	private Long costTime ;
	/** 
	 * 最近一次输出号码数量 
	 */ 
	private Long lastExpNum ;
	/** 
	 * 规则代码 
	 */ 
	private String ruleCode ;
	/** 
	 *  执行周期
	 */ 
	private String cron ;
	/** 
	 *  规则名称
	 */ 
	private String ruleName ;
	/** 
	 *  输出目录及文件名
	 */ 
	private String expFile ;
	/** 
	 * 导入脚本名称 
	 */ 
	private String impScript ;
	/** 
	 *  
	 */ 
	private String remarks ;
	/** 
	 *  规则描述
	 */ 
	private String ruleDesc ;
	/** 
	 *  URL规则
	 */ 
	private String ruleUrl ;
	/** 
	 *  关键字规则
	 */ 
	private String ruleKeyword ;
	/** 
	 *  APP规则
	 */ 
	private String ruleAppid ;
	
	public Long getId(){
		return this.id;
	}
	public void setId(Long id){
		this.id = id;
	}
	public java.util.Date getInsertTime(){
		return this.insertTime;
	}
	public void setInsertTime(java.util.Date insertTime){
		this.insertTime = insertTime;
	}
	public java.util.Date getLastRunTime(){
		return this.lastRunTime;
	}
	public void setLastRunTime(java.util.Date lastRunTime){
		this.lastRunTime = lastRunTime;
	}
	public Long getTaskPriority(){
		return this.taskPriority;
	}
	public void setTaskPriority(Long taskPriority){
		this.taskPriority = taskPriority;
	}
	public Long getRunStatus(){
		return this.runStatus;
	}
	public void setRunStatus(Long runStatus){
		this.runStatus = runStatus;
	}
	public Long getCostTime(){
		return this.costTime;
	}
	public void setCostTime(Long costTime){
		this.costTime = costTime;
	}
	public Long getLastExpNum(){
		return this.lastExpNum;
	}
	public void setLastExpNum(Long lastExpNum){
		this.lastExpNum = lastExpNum;
	}
	public String getRuleCode(){
		return this.ruleCode;
	}
	public void setRuleCode(String ruleCode){
		this.ruleCode = ruleCode;
	}
	public String getCron(){
		return this.cron;
	}
	public void setCron(String cron){
		this.cron = cron;
	}
	public String getRuleName(){
		return this.ruleName;
	}
	public void setRuleName(String ruleName){
		this.ruleName = ruleName;
	}
	public String getExpFile(){
		return this.expFile;
	}
	public void setExpFile(String expFile){
		this.expFile = expFile;
	}
	public String getImpScript(){
		return this.impScript;
	}
	public void setImpScript(String impScript){
		this.impScript = impScript;
	}
	public String getRemarks(){
		return this.remarks;
	}
	public void setRemarks(String remarks){
		this.remarks = remarks;
	}
	public String getRuleDesc(){
		return this.ruleDesc;
	}
	public void setRuleDesc(String ruleDesc){
		this.ruleDesc = ruleDesc;
	}
	public String getRuleUrl() {
		return ruleUrl;
	}
	public void setRuleUrl(String ruleUrl) {
		this.ruleUrl = ruleUrl;
	}
	public String getRuleKeyword() {
		return ruleKeyword;
	}
	public void setRuleKeyword(String ruleKeyword) {
		this.ruleKeyword = ruleKeyword;
	}
	public String getRuleAppid() {
		return ruleAppid;
	}
	public void setRuleAppid(String ruleAppid) {
		this.ruleAppid = ruleAppid;
	}
	
}